// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in ent_test/ent/runtime.go

const (
	Version = "v0.10.1-0.20220210141757-a7beb5c834f0"           // Version of ent codegen.
	Sum     = "h1:N/WKNehF44oag5ztRqI/aTt+5mT2rjUtXQwdrMnGSIE=" // Sum of ent codegen.
)
